### PR TITLE
Draft-quality Python 3.4 support

### PR DESCRIPTION
**Pull request by piannucci**
Opening a new PR extending https://github.com/scipy/weave/pull/1.  Not all tests pass, but my own applications work correctly.

Open questions remain regarding how str/bytes should be handled, how file objects should be handled, and how/if the codebase can simultaneously support Python 2 and 3.

### CODE REVIEW

**Comment by pv** [comment]
FWIW, https://github.com/pv/scipy-work/commit/196829a3fbe4d41a228445331131f206fae89599, not sure if useful any more though

Some comments based on a quick browse:

- Numpy takes char* == bytes, insisting on no data conversions.
- Handling file objects is [sort of possible to do](https://github.com/numpy/numpy/blob/master/numpy/core/include/numpy/npy_3kcompat.h#L141), but it's an evil hack, and requires inserting cleanup code after the file handle is no longer needed, so it IMHO is a reasonable choice to not provide automatic conversions at all on Python 3. If needed, users can pass in the `fileno()` integers themselves.
- Maintaining two code bases for Py2 and Py3 is usually a no-go, and usually just adding the `if sys.version_info[0] >= 3` statements is enough.

**Comment by rgommers** [comment]
@piannucci this PR needs a rebase now. When you push an update then the TravisCI tests will run (just enabled them) in order to verify that nothing broke on Python 2.6 / 2.7.

**Comment by piannucci** [comment]
Okay, rebased.  Also did some housekeeping.  Can someone set up Travis to test Python 3.4?

**Comment by pv** [comment]
I think you can set up the test yourself -- edit .travis.yml and
copypaste the python 2.7 section in the beginning.

**Comment by piannucci** [comment]
Is it a problem that through scipy.six we've added a dependency on scipy itself?

**Comment by rgommers** [comment]
> Is it a problem that through scipy.six we've added a dependency on scipy itself?

That's the part that I just ripped out, so you put it back by accident in the rebase it looks like. The dependency isn't needed.

**Comment by rgommers** [comment]
The tests failed, but the log only shows the scipy build.

**Comment by piannucci** [comment]
My bad.  Still a ton of conditional code to put in to restore Python 2 compatibility.

**Comment by piannucci** [comment]
Hm, that's a lot more errors than I get on my machine.  GCC seems unhappy.

**Comment by piannucci** [comment]
Test failures on Python 3.4 down to 2 on Travis, zero on my machine.

**Comment by piannucci** [comment]
Though there is some spew from a blitz expression that fails to compile.  Which is really two bugs: one in weave.blitz, one in the test.

**Comment by piannucci** [comment]
Hm, I'm seeing non-deterministic test failures.

**Pull request merged**
